version: '3.8'

services:
  mongodb:
    
    image: mongo:latest  
    container_name: mongodb_container 
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  
      MONGO_INITDB_ROOT_PASSWORD: example 
      MONGO_INITDB_DATABASE: connect_four_db 
    volumes:
      - mongo_data:/data/db  

volumes:
  mongo_data:
    driver: local
